import assert from 'node:assert/strict'
import test from 'node:test'
import {ReadlineState} from '../src/ui/readline-state.js'

const press = (state, name, modifiers = {}) => state.handleKey(null, {name, ...modifiers})
const ctrl = (state, name) => press(state, name, {ctrl: true})
const meta = (state, name) => press(state, name, {meta: true})

test('readline moves and edits at bounded Unicode code-point positions with keyboard aliases', () => {
  for (const [home, end, left, right, remove] of [
    ['home', 'end', 'left', 'right', 'delete'], ['a', 'e', 'b', 'f', 'd'],
  ]) {
    const state = new ReadlineState({value: 'a密🔑z'})
    const modifiers = home === 'a' ? {ctrl: true} : {}
    assert.equal(state.cursor, 4)
    press(state, right, modifiers)
    assert.equal(state.cursor, 4)
    press(state, home, modifiers)
    press(state, left, modifiers)
    assert.equal(state.cursor, 0)
    press(state, right, modifiers)
    state.handleKey('X')
    assert.equal(state.value, 'aX密🔑z')
    press(state, remove, modifiers)
    assert.equal(state.value, 'aX🔑z')
    press(state, end, modifiers)
    press(state, remove, modifiers)
    assert.equal(state.value, 'aX🔑z')
    press(state, left, modifiers)
    press(state, 'backspace')
    assert.equal(state.value, 'aXz')
    assert.equal(state.cursor, 2)
  }
})

test('readline word movement and deletion handle repeated whitespace and Unicode', () => {
  const state = new ReadlineState({value: 'one  two\t三'})
  meta(state, 'b')
  assert.equal(state.cursor, 9)
  meta(state, 'b')
  assert.equal(state.cursor, 5)
  meta(state, 'f')
  assert.equal(state.cursor, 8)
  meta(state, 'f')
  assert.equal(state.cursor, 10)
  meta(state, 'f')
  assert.equal(state.cursor, 10)
  meta(state, 'b')
  meta(state, 'b')
  meta(state, 'd')
  assert.equal(state.value, 'one  \t三')
  assert.equal(state.cursor, 5)
  ctrl(state, 'y')
  assert.equal(state.value, 'one  two\t三')
  assert.equal(state.cursor, 8)
  ctrl(state, 'w')
  assert.equal(state.value, 'one  \t三')
  ctrl(state, 'y')
  assert.equal(state.value, 'one  two\t三')
})

test('readline kill and yank preserve the exact text on either side of the cursor', () => {
  const state = new ReadlineState({value: 'say hello now'})
  ctrl(state, 'a')
  for (let i = 0; i < 4; i++) ctrl(state, 'f')
  ctrl(state, 'k')
  assert.equal(state.value, 'say ')
  assert.equal(state.cursor, 4)
  ctrl(state, 'y')
  assert.equal(state.value, 'say hello now')
  for (let i = 0; i < 4; i++) ctrl(state, 'b')
  ctrl(state, 'u')
  assert.equal(state.value, ' now')
  assert.equal(state.cursor, 0)
  ctrl(state, 'y')
  assert.equal(state.value, 'say hello now')
  assert.equal(state.cursor, 9)
  ctrl(state, 'w')
  assert.equal(state.value, 'say  now')
  assert.equal(state.cursor, 4)
  ctrl(state, 'y')
  assert.equal(state.value, 'say hello now')
})

test('readline transposes whole characters at the cursor and end without crossing the start', () => {
  const state = new ReadlineState({value: 'acb'})
  ctrl(state, 't')
  assert.equal(state.value, 'abc')
  assert.equal(state.cursor, 3)
  ctrl(state, 'a')
  ctrl(state, 't')
  assert.equal(state.value, 'abc')
  ctrl(state, 'f')
  ctrl(state, 't')
  assert.equal(state.value, 'bac')
  assert.equal(state.cursor, 2)
  const unicode = new ReadlineState({value: 'a🔑'})
  ctrl(unicode, 't')
  assert.equal(unicode.value, '🔑a')
  assert.equal(unicode.cursor, 2)
})

test('readline joins fragmented surrogate pairs and edits them as one character', () => {
  const state = new ReadlineState({value: 'abc'})
  ctrl(state, 'a')
  ctrl(state, 'f')
  state.handleKey('\ud83d')
  state.handleKey('\udd11')
  assert.equal(state.value, 'a🔑bc')
  assert.equal(state.cursor, 2)
  ctrl(state, 'b')
  ctrl(state, 'd')
  assert.equal(state.value, 'abc')
  state.handleKey('密🔑')
  assert.equal(state.value, 'a密🔑bc')
  assert.equal(state.cursor, 3)
  press(state, 'backspace')
  assert.equal(state.value, 'a密bc')
  assert.equal(state.cursor, 2)
})

test('readline returns completion actions without inserting terminal control characters', () => {
  const state = new ReadlineState({value: 'query'})
  assert.equal(state.handleKey('\r', {name: 'enter'}), 'submit')
  assert.equal(state.handleKey('\r', {name: 'return'}), 'submit')
  assert.equal(state.handleKey('\x1b', {name: 'escape'}), 'cancel')
  for (const character of ['\x00', '\x1b', '\x7f']) state.handleKey(character)
  assert.equal(state.value, 'query')
  assert.equal(state.cursor, 5)
  state.handleKey('\t')
  assert.equal(state.value, 'query\t')
})

test('readline browses history with both key pairs, retains drafts, and leaves history untouched', () => {
  for (const modifiers of [{}, {ctrl: true}]) {
    const history = ['first', 'second']
    const state = new ReadlineState({value: 'draft', history})
    const previous = modifiers.ctrl ? 'p' : 'up'
    const next = modifiers.ctrl ? 'n' : 'down'
    state.handleKey(' edited')
    press(state, previous, modifiers)
    assert.equal(state.value, 'second')
    assert.equal(state.cursor, 6)
    press(state, previous, modifiers)
    press(state, previous, modifiers)
    assert.equal(state.value, 'first')
    press(state, next, modifiers)
    assert.equal(state.value, 'second')
    press(state, next, modifiers)
    press(state, next, modifiers)
    assert.equal(state.value, 'draft edited')
    assert.equal(state.cursor, 12)
    assert.deepEqual(history, ['first', 'second'])
  }
})

test('readline skips an already-displayed newest entry on the first Up or Ctrl-P', () => {
  for (const key of [{name: 'up'}, {name: 'p', ctrl: true}]) {
    const state = new ReadlineState({value: 'newest', history: ['oldest', 'previous', 'newest']})
    state.handleKey(null, key)
    assert.equal(state.value, 'previous')
    state.handleKey(null, key)
    assert.equal(state.value, 'oldest')
    press(state, 'down')
    press(state, 'down')
    assert.equal(state.value, 'newest')
  }
})

test('readline treats edits to a prefilled history entry as a restorable draft', () => {
  const state = new ReadlineState({value: 'newest', history: ['previous', 'newest']})
  state.handleKey(' draft')
  ctrl(state, 'p')
  assert.equal(state.value, 'newest')
  ctrl(state, 'n')
  assert.equal(state.value, 'newest draft')
  const empty = new ReadlineState({value: 'draft'})
  assert.equal(ctrl(empty, 'p'), null)
  assert.equal(press(empty, 'down'), null)
  assert.equal(empty.value, 'draft')
  const single = new ReadlineState({value: 'only', history: ['only']})
  ctrl(single, 'p')
  ctrl(single, 'p')
  assert.equal(single.value, 'only')
})
